apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: surrealdb-data
  namespace: surrealdb
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: "standard"