apiVersion: v1
kind: Service
metadata:
  name: surrealdb
  namespace: surrealdb
  labels:
    app: surrealdb
spec:
  ports:
  - port: 8000
    protocol: TCP
  selector:
    app: surrealdb
  type: NodePort