apiVersion: v1
kind: Service
metadata:
  name: surrealdb-tikv
  namespace: surrealdb-tikv
  labels:
    app: surrealdb-tikv
spec:
  ports:
  - port: 8000
    protocol: TCP
  selector:
    app: surrealdb-tikv
  type: NodePort